### ISSUE TITLE
Disappearing contacts

### ISSUE THREAD

**Issue by 78kfb** [Beldex-Coin/bchat-android#10]
Personal chats have a great feature, you can set a timer and messages will automatically disappear. When I turn this feature on, a service message appears in the chat. 
![image](https://user-images.githubusercontent.com/117159924/203040885-2c61fd0e-8aa3-40ca-830a-f44e7d371e8b.png)
And when the timer goes off, all the messages are erased and only this service message remains in the chat. The function works well and correctly.

But there is a problem. In the settings there is a function of cropping the history of chats. 
![image](https://user-images.githubusercontent.com/117159924/203041170-ad9e6f58-ca63-4417-ab19-a7ad60a4105a.png)
Which deletes messages to the required value, which you can specify yourself. If you turn it on, it will also delete the service message about the timer. 

And as soon as you have disappeared all messages on the timer, in a private chat does not remain a single message, the chat will be empty. Which is good and right. But as the chat becomes empty, it is DELETED from your list of chats and you can not write to this person again, because the chat is gone.

**Comment by snowman-45** [comment]
So in this scenario this, will become exactly similar to deleting all the messages from a contact. Which removes the contact from your contact list. 
We will resolve this in our upcoming release.
