### ISSUE TITLE
Repeating notifications does not work

### ISSUE THREAD

**Issue by 78kfb** [Beldex-Coin/bchat-android#11]
In the settings there is a function, I turned on the repetition of 3 times, but all the time I used the program I have never heard a repeated notification. 
![image](https://user-images.githubusercontent.com/117159924/203043556-7742124c-d7fc-422f-be65-8bf80d14ac08.png)
I also do not understand the scheme of this function, it is triggered by a timer or what? What are the conditions for me to get a repeat notification?

**Comment by snowman-45** [comment]
We have removed this feature for now.
