### ISSUE TITLE
Very big borders of block of text

### ISSUE THREAD

**Issue by 78kfb** [Beldex-Coin/bchat-android#12]
The borders in the "blocks of text" in the chats are too big. It turns out ugly. It is necessary to reduce the borders a little (marked with a red arrow). In the photo you can see that the block with text touching the timer icon. This is wrong.
![IMG_20221121_135747](https://user-images.githubusercontent.com/117159924/203048389-96c27863-b304-4645-8d6d-092de312e4da.jpg)

When you respond to a message, again there are huge indents in the text blocks. This is not right. These borders can safely reduce by 2-3 times.
![IMG_20221121_145958](https://user-images.githubusercontent.com/117159924/203049186-0d322411-d020-47ad-8344-66aa6e9410aa.jpg)

**Comment by snowman-45** [comment]
Thanks @78kfb , great suggestion. Will fix this in upcoming release.

**Comment by snowman-45** [comment]
Fixed in BChat 2.0.0 release.
