### ISSUE TITLE
Not an issue: just need help installing without Google Play

### ISSUE THREAD

**Issue by link-leocorde** [Beldex-Coin/bchat-android#31]
Sorry, wasn't sure how else to ask.: How can I install bchat through f-droid instead of using Google Play? I tried pasting the link for the releases as a repo but that didn't work.

- [x] I have read and agree to adhere to the [Code of Conduct].
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

**Comment by lfom** [comment]
This is not how F-Droid works, BChat devs would have to setup a F-Droid repo, what would be great by the way.

If you don't want to use PlayStore and keep the app up-to-date with new releases then you can use Aurora Droid (it will download it from PS tho) or install Obtainium and add the GitGib project repo address (or search for it and choose the correct one, from Beldex-coin.

**Comment by link-leocorde** [comment]
Thanks for the help!
