### ISSUE TITLE
A bug in belnet and BNS domain purchase

### ISSUE THREAD

**Issue by Rajwaar** [Beldex-Coin/bchat-android#50]
**Code of conduct**
In purchase of BNS domains couldn’t find the existing or purchased BNS id on the initial stage of purchase on typing the BNS what we like to buy…. We are getting to know it only after we enter all the complete data
And the issue on belnet is the node is very slow and couldn’t use the internet, its like 2G may be slower that 2G….. all nodes are slow I have verified.

**Comment by snowman-45** [comment]
Please post these issues on the respective working repositories. 
We would love to help if there is any issue which you're facing in BChat.
