### ISSUE TITLE
Bchat crashes when you hit the button "help" in settings menu.

### ISSUE THREAD

**Issue by 78kfb** [Beldex-Coin/bchat-android#6]
Bchat crashes when you hit the button "help" in settings menu.

Phone - oppo a96
Android 12
App version 1.2.1

**Comment by snowman-45** [comment]
Hi @78kfb please check you have permissions to access your gmail from other applications, as this feature seems like working all the device we tested.
Can you please share the crash report so that we can check.

**Comment by 78kfb** [comment]
> Hi @78kfb please check you have permissions to access your gmail from other applications, as this feature seems like working all the device we tested. Can you please share the crash report so that we can check.

Dear snowman-45, I get it. You are redirecting to the mail app. I don't have a mail app installed.

**Comment by snowman-45** [comment]
Similar to #7
