### ISSUE TITLE
Graphic button issue, when start new chat.

### ISSUE THREAD

**Issue by 78kfb** [Beldex-Coin/bchat-android#8]
https://user-images.githubusercontent.com/117159924/199715088-4d3be591-d5d9-4137-979a-cfe90d675904.mp4

Some glitches when trying start new chat. Buttons don't press, you must move button, but you don see it.

Phone oppo a96
Android 12
Bchat App 1.2.1

**Comment by snowman-45** [comment]
Hi @78kfb There are two things you can do with this button 

1. Click the button, it will expand and you can click on one of three options
2. Hold the button and move towards the any of three option you want to use, It will start the new action.

**Comment by snowman-45** [comment]
Hi Please try this and let me know if it is working. 
Just hold the button and move it towards all three options(New chat, Secret group, Social Group)  and let me know if the respective option is getting clicked.

**Comment by 78kfb** [comment]
Yes, that's how it works. But there are graphical problems. These are shown in the video. When you slide your finger on the screen, it works correctly and is drawn only for one to one chats.

**Comment by snowman-45** [comment]
This issue has been fixed. It will be live in our upcoming release.
